export const config = {
  countries: [
    {
      name: "India",
      flag: "/assets/in.png",
    },
    {
      name: "Australia",
      flag: "/assets/au.png",
    },
    {
      name: "Brasil",
      flag: "/assets/br.png",
    },
    {
      name: "Canada",
      flag: "/assets/ca.png",
    },
    {
      name: "Chile",
      flag: "/assets/cl.png",
    },
    {
      name: "Czech Republic",
      flag: "/assets/cz.png",
    },
    {
      name: "Indonesia",
      flag: "/assets/id.png",
    },
    {
      name: "Ireland",
      flag: "/assets/ie.png",
    },
    {
      name: "Italy",
      flag: "/assets/it.png",
    },
    {
      name: "Lebanon",
      flag: "/assets/lb.png",
    },
    {
      name: "Malaysia",
      flag: "/assets/my.png",
    },
    {
      name: "New Zealand",
      flag: "/assets/nz.png",
    },
    {
      name: "Philippines",
      flag: "/assets/ph.png",
    },
    {
      name: "Poland",
      flag: "/assets/pl.png",
    },
    {
      name: "Portugal",
      flag: "/assets/pt.png",
    },
    {
      name: "Qatar",
      flag: "/assets/qa.png",
    },
    {
      name: "Singapore",
      flag: "/assets/sg.png",
    },
    {
      name: "Slovakia",
      flag: "/assets/sk.png",
    },
    {
      name: "South Africa",
      flag: "/assets/za.png",
    },
    {
      name: "Sri Lanka",
      flag: "/assets/lk.png",
    },
    {
      name: "Turkey",
      flag: "/assets/tr.png",
    },
    {
      name: "UAE",
      flag: "/assets/ae.png",
    },
    {
      name: "United Kingdom",
      flag: "/assets/gb.png",
    },
    {
      name: "United States",
      flag: "/assets/us.png",
    },
  ],
  indiaRestaurants: [
    { label: "Agra Restaurants", redirectLink: "" },
    { label: "Ahmedabad Restaurants", redirectLink: "" },
    { label: "Ajmer Restaurants", redirectLink: "" },
    { label: "Alappuzha Restaurants", redirectLink: "" },
    { label: "Allahabad Restaurants", redirectLink: "" },
    { label: "Amravati Restaurants", redirectLink: "" },
    { label: "Amritsar Restaurants", redirectLink: "" },
    { label: "Aurangabad Restaurants", redirectLink: "" },
    { label: "Bengaluru Restaurants", redirectLink: "" },
    { label: "Bhopal Restaurants", redirectLink: "" },
    { label: "Bhubaneswar Restaurants", redirectLink: "" },
    { label: "Chandigarh Restaurants", redirectLink: "" },
    { label: "Chennai Restaurants", redirectLink: "" },
    { label: "Coimbatore Restaurants", redirectLink: "" },
    { label: "Cuttack Restaurants", redirectLink: "" },
    { label: "Darjeeling Restaurants", redirectLink: "" },
    { label: "Dehradun Restaurants", redirectLink: "" },
    { label: "Delhi NCR Restaurants", redirectLink: "" },
    { label: "Dharamshala Restaurants", redirectLink: "" },
    { label: "Gangtok Restaurants", redirectLink: "" },
    { label: "Goa Restaurants", redirectLink: "" },
    { label: "Gorakhpur Restaurants", redirectLink: "" },
    { label: "Guntur Restaurants", redirectLink: "" },
    { label: "Guwahati Restaurants", redirectLink: "" },
    { label: "Gwalior Restaurants", redirectLink: "" },
    { label: "Haridwar Restaurants", redirectLink: "" },
    { label: "Hyderabad Restaurants", redirectLink: "" },
    { label: "Indore Restaurants", redirectLink: "" },
    { label: "Jabalpur Restaurants", redirectLink: "" },
    { label: "Jaipur Restaurants", redirectLink: "" },
    { label: "Jalandhar Restaurants", redirectLink: "" },
    { label: "Jammu Restaurants", redirectLink: "" },
    { label: "Jamnagar Restaurants", redirectLink: "" },
    { label: "Jamshedpur Restaurants", redirectLink: "" },
    { label: "Jhansi Restaurants", redirectLink: "" },
    { label: "Jodhpur Restaurants", redirectLink: "" },
    { label: "Junagadh Restaurants", redirectLink: "" },
    { label: "Kanpur Restaurants", redirectLink: "" },
    { label: "Khajuraho Restaurants", redirectLink: "" },
    { label: "Khamgaon Restaurants", redirectLink: "" },
    { label: "Kharagpur Restaurants", redirectLink: "" },
    { label: "Kochi Restaurants", redirectLink: "" },
    { label: "Kolhapur Restaurants", redirectLink: "" },
    { label: "Kolkata Restaurants", redirectLink: "" },
    { label: "Kota Restaurants", redirectLink: "" },
    { label: "Lucknow Restaurants", redirectLink: "" },
    { label: "Ludhiana Restaurants", redirectLink: "" },
    { label: "Madurai Restaurants", redirectLink: "" },
    { label: "Manali Restaurants", redirectLink: "" },
    { label: "Mangalore Restaurants", redirectLink: "" },
    { label: "Manipal Restaurants", redirectLink: "" },
    { label: "Meerut Restaurants", redirectLink: "" },
    { label: "Mumbai Restaurants", redirectLink: "" },
    { label: "Mussoorie Restaurants", redirectLink: "" },
    { label: "Mysore Restaurants", redirectLink: "" },
    { label: "Nagpur Restaurants", redirectLink: "" },
    { label: "Nainital Restaurants", redirectLink: "" },
    { label: "Nashik Restaurants", redirectLink: "" },
    { label: "Neemrana Restaurants", redirectLink: "" },
    { label: "Ooty Restaurants", redirectLink: "" },
    { label: "Palakkad Restaurants", redirectLink: "" },
    { label: "Patiala Restaurants", redirectLink: "" },
    { label: "Patna Restaurants", redirectLink: "" },
    { label: "Puducherry Restaurants", redirectLink: "" },
    { label: "Pune Restaurants", redirectLink: "" },
    { label: "Pushkar Restaurants", redirectLink: "" },
    { label: "Raipur Restaurants", redirectLink: "" },
    { label: "Rajkot Restaurants", redirectLink: "" },
    { label: "Ranchi Restaurants", redirectLink: "" },
    { label: "Rishikesh Restaurants", redirectLink: "" },
    { label: "Salem Restaurants", redirectLink: "" },
    { label: "Shimla Restaurants", redirectLink: "" },
    { label: "Siliguri Restaurants", redirectLink: "" },
    { label: "Srinagar Restaurants", redirectLink: "" },
    { label: "Surat Restaurants", redirectLink: "" },
    { label: "Thrissur Restaurants", redirectLink: "" },
    { label: "Tirupati Restaurants", redirectLink: "" },
    { label: "Trichy Restaurants", redirectLink: "" },
    { label: "Trivandrum Restaurants", redirectLink: "" },
    { label: "Udaipur Restaurants", redirectLink: "" },
    { label: "Vadodara Restaurants", redirectLink: "" },
    { label: "Varanasi Restaurants", redirectLink: "" },
    { label: "Vellore Restaurants", redirectLink: "" },
    { label: "Vijayawada Restaurants", redirectLink: "" },
    { label: "Visakhapatnam Restaurants", redirectLink: "" },
  ],
};
// 89
